version: "3.8"

services:
  host_mongo:
    image: mongo:5.0.8
    command: mongod
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /home/linux/data/mongo/db:/data/db
      - /home/linux/data/mongo/configdb:/data/configdb
    container_name: host_mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: host_mongo
    depends_on:
      - host_mongo
